### ISSUE TITLE
make reactive joins with ReactJS

### ISSUE THREAD

**Issue by JWDobken** [reactjs/react-meteor#109]
Have been struggling with this for really long; with my Meteor+ReactJS app, I want to have a reactive join between the `MainCollection` and the `SubCollection`. And the PublishComposite might just be what I need. However, when the SubCollection is updated, this is not reactive!

does anyone know how to make a client-side reactive join?

**server code**

    import { publishComposite } from 'meteor/reywood:publish-composite';
    Meteor.MainCollection('maincollection.pub.all', {
      find: function () {
        return MainCollection.find();
      },
      children: [
        {
          find: function (doc) {
            return SubCollection.find(
              { mainCollectionId: doc._id },
              {
                sort: { createdAt: -1 }, limit: 1,
                fields: {
                  completedAt: 1,
                  mainCollectionId: 1,
                }
              })
          }
        }
      ]
    });

**client container**

    export default createContainer(() => {
      let mainCollectionSub = Meteor.subscribe('maincollection.pub.all');
      options = {
        transform: function (doc) {
          doc.subcollection = SubCollection.findOne({
            mainCollectionId: doc._id }, ).fetch();
          return doc;
        }
      }
        var maincollection = MainCollection.find({}, options).fetch();
      return {
        maincollection: MainCollection.find({}, options).fetch(),
      }
    }, MainCollectionView);

**Comment by Ramyace4455** [comment]
I think the right way to do this on the client is to use a collection helper - I'm not sure that transform is actually reactive in that way: https://guide.meteor.com/collections.html#collection-helpers

Regards,
[ReactJS Online Training](http://www.courseing.com/learn/reactjs-online-training)
