### ISSUE TITLE
Use atmospherejs to distribute this package.

### ISSUE THREAD

**Issue by lijunle** [reactjs/react-meteor#20]
[Atmospherejs][1] is a package store for Meteor. It use [Meteorite][2] to manage package.

[1]: http://atmospherejs.com/
[2]: http://oortcloud.github.io/meteorite/

Here is the [guide][3]. Why not use it?

[3]: http://atmospherejs.com/docs/publishing

**Comment by alexhancock** [comment]
I never got around to this, but I just looked back in on the situation and found this...

https://atmospherejs.com/hipertracker/reactjs

They have done a good job from what I can tell. I just built a simple test app with it, and it worked well for me.

**Comment by benjamn** [comment]
Done! https://atmospherejs.com/reactjs/react

**Comment by alexhancock** [comment]
Thanks, Ben!
