### ISSUE TITLE
React sub-modules, routing

### ISSUE THREAD

**Issue by aksonov** [reactjs/react-meteor#25]
It is not clear from demo, how to split React components to many files effectively. How to use routing, Flux approach, etc. because Meteor supports node 'require' only on server side... Again, maybe it is not issue of react-meteor but Meteor framework.

**Comment by benjamn** [comment]
I think it used to be true (with React v0.10.0) that your `.jsx` files had to have `/** @jsx React.DOM */` at the top in order for JSX syntax to be transformed, so all those opening `<`s were syntax errors in new files if you neglected to include that comment.

This should no longer be true with React v0.12.2. If this diagnosis is mistaken, please feel free to reopen this issue!

**Comment by trusktr** [comment]
@SunspotsEU 

> there has to be a better way to do this, instead of sidestepping around Meteor.

Meteor code runs on the server side. I bet there's a way to run webpack during Meteor's build stage instead of doing it manually.

@aksonov So when you run the webpacked version of React, does it work fine with `ReactMeteor.Mixin`? Could you post a sample snippet?

**Comment by tehfailsafe** [comment]
I'd also like to know about this. Using ./components folder with webpack sounds like a great idea, but I have also come to really appreciate the getMeteorState reactivity. It sounds like with using @aksonov approach we'd be sidestepping react-meteor all together and losing it's meteor specific features. 

Is that right?
