### ISSUE TITLE
separate of logic from presentation not possible?

### ISSUE THREAD

**Issue by Maxhodges** [reactjs/react-meteor#26]
I'm a Meteor dev and was curious about React, but from looking at the example it seems the approach results in very poor separation of presentation from logic. Is it necessary to sacrifice good design if you want to use React with Meteor?

https://github.com/reactjs/react-meteor/blob/master/examples/leaderboard/leaderboard.jsx#L33-L64

**Comment by benjamn** [comment]
This is a good question, but it's part of the React™ philosophy that separation of logic and presentation is not actually a worthwhile goal. Rather, your code should be organized into reusable UI components, which include both logic and presentation. Here's a presentation by @petehunt that goes through the reasoning (starting on slide 11): http://www.slideshare.net/floydophone/react-preso-v2
