### ISSUE TITLE
Reactivity fails when props are changed

### ISSUE THREAD

**Issue by liron00** [reactjs/react-meteor#27]
Thanks for a great package, I've been using it to great success. Unfortunately I just discovered it has a pretty major bug.

The current implementation assumes that this._meteorComputation is dependent on whatever set of reactive data sources were accessed when getMeteorState was run at mount-time.

If props are changed, getMeteorState is re-run but *not in a reactive context*. The problem is that getMeteorState may access a dynamic set of reactive variables that depend on the current prop values, so the reactivity stops working once props are changed.

**Comment by benjamn** [comment]
You're right! This will be fixed soon.

**Comment by liron00** [comment]
Cool. Btw, I rolled my own Meteor-React integration which is much more elaborate.

Check out this demo: http://busterbros.meteor.com/
It's powered by this source code: http://pastebin.com/32qdGAXQ
