### ISSUE TITLE
script src?

### ISSUE THREAD

**Issue by Squ34k3rZ** [reactjs/react-meteor#34]
Should the html include the jsx script in the < head >, or is that automatically done with meteor?

This confused me when I first read the example and perhaps the community would benefit from a comment in the html code. Just a suggestion!

Thanks for your help

**Comment by benjamn** [comment]
Yep, Meteor bundles all your JavaScript together automatically and sends it down to the client: http://docs.meteor.com/#/full/structuringyourapp. Check out the HTML source of the example page, and you'll see a bunch of `<script>` tags (note: in production they are all combined into one file).
