### ISSUE TITLE
State and publications/subscriptions without Session - Question

### ISSUE THREAD

**Issue by tehfailsafe** [reactjs/react-meteor#37]
Working on my first component, a searchable users list. Trying to keep it simple to get started, however running into some conceptual difficulties.

If I subscribe to all users with `Meteor.subscribe('users');` and then filter them out with something like `title.indexOf(this.props.searchText) == -1`, won't I still be loading all 1000 (one day...) users? 

It would be best to setup a publication with the searchTerm, right? Something like `Meteor.publish("searchable_users", function (searchTerm, limit) { ... ` 

But it seems that `getMeteorState` is not updating reactively with `this.state.searchText`. If I change this to a Session variable and make the publication search using the Session var, it works fine, but this feels very un-react like doesn't it? The Session variables are completely out of scope with the react components, which are attempting to keep everything self contained and testable. Don't Session vars create additional state management that have to be dealt with?

Here's a code non-filtering example that should help illustrate. Am I misunderstanding something? 

``` javascript
if (Meteor.isServer) {
  Meteor.publish("searchable_users", function(searchTerm, limit) {
    return Meteor.users.find({
      "profile.name": {
        $regex: searchTerm,
        $options: 'i'
      }
    }, {
      limit: limit
    });
  });
}


if (Meteor.isClient) {
  var SearchableUserList = ReactMeteor.createClass({
    getInitialState: function() {
      return {
        searchText: ""
      };
    },
    startMeteorSubscriptions: function() {
      return Meteor.subscribe('searchable_users', this.state.searchText, 10);
    },
    getMeteorState: function() {
      // Also tried adding the find{$regex} function here, but doesn't work either
      return {
        users: Meteor.users.find()
      };
    },
    handleInput: function(searchText) {
      return this.setState({
        searchText: searchText
      });
    },
    render: function() {
      return (
        <div>
          <SearchInput
            inputText={this.state.searchText}
            handleInput={this.handleInput}
          />
          <BoxedList
            items={this.state.users}
            titleKey={'profile.name'}
          />
        </div>
      )
    }
  });

  var SearchInput = React.createClass({
    onChange: function() {
      return this.props.handleInput(this.refs.searchInput.getDOMNode().value);
    },
    render: function() {
      return (
        <div>
          <input
            type="text"
            ref="searchInput"
            value={this.props.inputText}
            onChange={this.onChange}
          />
        </div>
      )
    }
  });

  var BoxedList = React.createClass({
    render: function() {
      return (
        <div>
          {
            this.props.items.map (item) =>
              title = eval('item.' + this.props.titleKey)
              # return if title.indexOf(this.props.searchText) is -1
              <ListItem key={item._id} title={title} />
          }
        </div>

      )
    }
  });

  var ListItem = React.createClass({
    render: function() {
      return (
        <div>{this.props.title}</div>
      )
    }
  });
}

**Comment by benjamn** [comment]
Interesting, I think the problem is that the `Tracker.autorun` function is only re-run when `this.props` are changed, and not when `this.state` changes.

I think the solution might be to call `this._meteorStateDep.changed()` from `componentWillUpdate`, but perhaps only if `componentWillReceiveProps` was not called.

**Comment by tehfailsafe** [comment]
I see. It seems like we'd want to re-run `Tracker.autorun` especially on state changes, since those are where the user inputs are coming in. Am I thinking about the data flow correctly or am I overthinking?

I tried adding `this._meteorStateDep.changed()` on `comonentWillUpdate` but that crashed out the browser... I still can't even close the tab, even after stopping and restarting meteor and reconnecting in a new tab.

However adding `this._meteorStateDep.changed()` on the event handler where I set the state makes the whole thing work correctly.

The following works correctly, filters list (although seems a minor delay, not as responsive as the pure inside react version)
```javascript 
handleInput: function(searchText) {
    this.setState({
      searchText: searchText
    });
    this._meteorStateDep.changed();
  }
```

**Comment by benjamn** [comment]
I have a commit coming up that calls `this._meteorStateDep.changed()` from `componentWillUpdate`, and gets rid of `componentWillReceiveProps`.

The tricky part is that you're not supposed to call `this.setState` inside `componentWillUpdate` (I think it just gets ignored?), so the `Tracker.autorun` callback needs to queue up the states and apply them later (which also fixes #4).

**Comment by tehfailsafe** [comment]
Cool, in the meantime I'll just manually call `changed()` every time I set the state. I also tried creating another parent wrapper component that send the search text state down as props, and that did actually work, but seems silly to have a component that just handles input and passes it to another component that sets up the subscriptions etc.

**Comment by tehfailsafe** [comment]
Nevermind, you're fast!
Last thing, any idea why a page reload creates a blank list prior to adding any input, yet navigating away from the route and back correctly has it populated?
