### ISSUE TITLE
Why CDN?

### ISSUE THREAD

**Issue by ccorcos** [reactjs/react-meteor#43]
Is there any reason you add a script tag and use a CDN as opposed to packaging the js within this package? I noticed this today when I didn't have internet...

**Comment by hitchcott** [comment]
+1 - I'd consider this a bug.

Many of my deployments are on an internal network with no internet access.

**Comment by ccorcos** [comment]
You can use this in the meantime:

https://github.com/ccorcos/meteor-react

This package is also not opinionated about how you integrate meteor and react. I think thats a good idea for the react official package...
