### ISSUE TITLE
Use without mixin?

### ISSUE THREAD

**Issue by rolfnl** [reactjs/react-meteor#46]
With es6 and React 0.13 release that's pushing "try something else than a mixin" have you considered updating this so you can use it not as a mixing in React?
Also see: https://medium.com/@dan_abramov/mixins-are-dead-long-live-higher-order-components-94a0d2f9e750

I must admit that I haven't looked at the code yet, I'm already running out of time, so perhaps at this time it's maybe just not possible or refactoring might be a huge pile of work...(?)

**Comment by ahoereth** [comment]
Just did some research. Seems like while there is the raw possibility to use ES6 classes, it is not feasible if you need extend the default component behavior (like with react-meteor mixins). The general opinion seems to be to stick to `createClass` until react introduces an alternative to mixins.

Then again.. The reactjs:meteor-react project does not get too much attention currently, there are more active community projects doing very similar stuff.

**Comment by benjamn** [comment]
@ahoereth is right, though I would be interested to learn about any known techniques for implementing React components with ES6 classes in Meteor.
