### ISSUE TITLE
Possible to have first render server side, then everything else client side?

### ISSUE THREAD

**Issue by trusktr** [reactjs/react-meteor#47]
Is it possible to use meteor-routecore to render a page's initial HTML server-side, then the client takes over?

**Comment by trusktr** [comment]
Oops, I meant react-meteor, not meteor-routecore. I wonder if we can render React on the serverside to have nice initial page loads with the pre-determined HTML being sent to the browser.

**Comment by don-smith** [comment]
I was wondering the same thing. Has anyone got this working yet? Is it possible?

**Update**: Looks like it's not possible today. The existing discussion is taking place in #41.

**Comment by trusktr** [comment]
Yeah, let's close this for that one.
