### ISSUE TITLE
Separate jsx files

### ISSUE THREAD

**Issue by podo** [reactjs/react-meteor#51]
I’m having difficulties figuring out how to separate react components into `jsx` files and loading one of them as a child into another.

```javascript
var PostsList = ReactMeteor.createClass({
  ...
  render: function() {
    var children = this.state.posts.map(function(post) {
      return <Post key={post._id} title={post.title}/>
    })

    return (
      <div className="posts">
        { children }
      </div>
    );
  }
});

var Post = ReactMeteor.createClass({
  render: function() {
    return (
      <div className="post">
        {this.props.title}
      </div>
    );
  }
});
```
This seems to work as a single file, but I’m thinking if it’s possible to load have `Post` as a separate `jsx` template, because I’m getting this error: 
```
Exception from Tracker afterFlush function: Post is not defined
ReferenceError: Post is not defined
    at http://localhost:3000/client/views/postsList.jsx.js?2f15d1d2d163aef174c55b73f6c1dd1b386e7851:16:34
```

**Comment by giantelk** [comment]
Without using Meteor you would use require and export with something like
Browserify. Maybe Meteor will bundle/build if the files were renamed to .js

**Comment by podo** [comment]
Apparently, removing `var` from all templates fixed this. Not sure, if that’s the best possible way to resolve it, though.

**Comment by rgstephens** [comment]
Thanks, @podo
