### ISSUE TITLE
Separate Meteor Mixin from React source

### ISSUE THREAD

**Issue by ccorcos** [reactjs/react-meteor#56]
I think this package should only do 2 things: it should put React on the client and the server, and register a jsx build plugin. 

The meteor mixin stuff is nice, but its opinionated and I think it should be moved to another package so people can choose how they want to use React.

**Comment by ccorcos** [comment]
https://forums.meteor.com/t/react-package-for-meteor/2565

**Comment by benjamn** [comment]
I agree that the `ReactMixin` would be too opinionated for a core Meteor package, but this is not a core package. This package is just like any other Atmosphere package. It aims to provide a complete and reasonable way to integrate React with Meteor, and `ReactMixin` is an important part of that recommendation.
