### ISSUE TITLE
package not found when ROOT_URL environment variable defined

### ISSUE THREAD

**Issue by annachu** [reactjs/react-meteor#61]
Hello. Thanks so much for making this package!

I'm having trouble getting the file `react-with-addons*.js` to load when the ROOT_URL environment variable is set.

For example, if ROOT_URL is set to `http://localhost:3000/myApp`, I see that the `reactjs_react.js` file is correctly referenced in `<head>` as
`<script type="text/javascript" src="/myApp/packages/reactjs_react.js?..etc.."></script>`

But the `react-with-addons*.js` file shows up as
`<script src="/packages/reactjs_react/vendor/react-with-addons-0.13.0.js"></script>`
without the root path prefix.

Is there a way I could get around this? Thanks!

**Comment by benjamn** [comment]
This should be fixed in the latest package release (0.2.2)!

**Comment by annachu** [comment]
Yay - it works!  Thanks so much!!
