### ISSUE TITLE
How usable is this?

### ISSUE THREAD

**Issue by Charuru** [reactjs/react-meteor#7]
As the title asks. I'm not too into Meteor's UI system and am curious if this could replace it entirely. I want to try some side projects with Meteor but don't want to do them before the new UI system is out for Meteor, but if this package could supplant Meteor's new UI system that would be fantastic.

Thanks for listening to my rambly questions.

**Comment by benjamn** [comment]
I'm in the process of updating this project after a very long stagnation, and I'm glad to say it will be much more usable!
