### ISSUE TITLE
using es6 with jsx?

### ISSUE THREAD

**Issue by rkstar** [reactjs/react-meteor#72]
can we use es6 jsx --harmony in this package?  https://github.com/hipertracker/meteor-reactjs/  has implemented this.

i would love to see this in the "official" react-meteor package.

**Comment by ahoereth** [comment]
Works fine for me. See https://github.com/reactjs/react-meteor/commit/90d179f40974a547744cf9f7205d35b7a720231f

**Comment by rkstar** [comment]
agreed. closing.
