### ISSUE TITLE
React components never removed from DOM

### ISSUE THREAD

**Issue by hmeerlo** [reactjs/react-meteor#76]
Hi,

I'm probably doing something wrong, but I couldn't resist trying react-meteor out. I have added one page in my app which uses react-meteor for it's ui. It works just fine as I visit the page, but when I navigate away to another page the react component are not removed. If I then revisit the page a duplicate of the components is added etc. So how should I cleanup the DOM when navigating away?

Regards,
Herman

**Comment by hmeerlo** [comment]
Is this project dead as a dodo? No reactions on any of the latest issues.

**Comment by xcen** [comment]
Is there a way to manually consume this fix as painlessly as possible? I'm facing the same issue.

**Comment by hmeerlo** [comment]
Hi xcen,

you could just clone my repo https://github.com/hmeerlo/react-meteor/ This one looks pretty dead to me.

/Herman
