### ISSUE TITLE
Use components defined in packages

### ISSUE THREAD

**Issue by merunga** [reactjs/react-meteor#79]
In the example if I move the ```leaderboard.jsx``` file into a package, the template ```Leaderboard``` is not found:
```Uncaught Error: No such template: Leaderboard```
in ```blaze/lookup.js```

Here's a [reproduction repo](https://github.com/merunga/meteor-react-no-such-template), deployed [here](http://meteor-react-no-such-template.meteor.com/).

**Comment by froatsnook** [comment]
Don't forget to export the variable:

```javascript
api.export("Leaderboard", ["client", "server"]);
```

As a rule, variables for packages:
* with `var` => file only
* without `var` => package only
* without `var` and in `api.export` => available to app

**Comment by merunga** [comment]
Templates are always exported, aren't they? And the react mixin creates a real spacebar template, doesn't it? Or maybe i don't completely get how it works...

Either way, I tried what you said, didn't work either.

@froatsnook are you using react components inside your packages already?

**Comment by froatsnook** [comment]
@merunga No, I'm not using react components inside packages.  At first glance it looked like a generic package export problem.

I'll take a look :)

**Comment by froatsnook** [comment]
OK at least the Leaderboard variable is now exported by the package.  So you could do:

```javascript
Template.yourTemplate.onRendered(function() {
    var container = this.find("#container");
    React.render(React.createElement(Leaderboard, { }), container);
});
```

This is definitely a react-meteor bug.  It needs `api.use("templating")` in package.js.  I submitted a pull request, but not sure when it will be merged in.  I guess you could clone react-meteor and cherry-pick this request?  Also make sure to check out #77.  I'm currently working from a local copy!

**Comment by merunga** [comment]
I cloned locally the package and added ```templating``` to the dependencies... that did the trick. Thanks @froatsnook !
